//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeatherApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyWeatherApp.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Weather.
        /// </summary>
        public static string CurrentWeatherTitle {
            get {
                return ResourceManager.GetString("CurrentWeatherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load data..
        /// </summary>
        public static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feels like: {0:F0}°.
        /// </summary>
        public static string FeelsLike {
            get {
                return ResourceManager.GetString("FeelsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Forecast.
        /// </summary>
        public static string HourlyForecastTitle {
            get {
                return ResourceManager.GetString("HourlyForecastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity: {0}%.
        /// </summary>
        public static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated: {0:HH:mm}.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading weather forecast....
        /// </summary>
        public static string LoadingWeather {
            get {
                return ResourceManager.GetString("LoadingWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-Day Forecast.
        /// </summary>
        public static string SevenDayForecastTitle {
            get {
                return ResourceManager.GetString("SevenDayForecastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed..
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Sky.
        /// </summary>
        public static string WeatherClear {
            get {
                return ResourceManager.GetString("WeatherClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dulksna.
        /// </summary>
        public static string WeatherDrizzle {
            get {
                return ResourceManager.GetString("WeatherDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fog.
        /// </summary>
        public static string WeatherFog {
            get {
                return ResourceManager.GetString("WeatherFog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather for {0}.
        /// </summary>
        public static string WeatherFor {
            get {
                return ResourceManager.GetString("WeatherFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Rain.
        /// </summary>
        public static string WeatherHeavyRain {
            get {
                return ResourceManager.GetString("WeatherHeavyRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Snow.
        /// </summary>
        public static string WeatherHeavySnow {
            get {
                return ResourceManager.GetString("WeatherHeavySnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mainly Clear.
        /// </summary>
        public static string WeatherMainlyClear {
            get {
                return ResourceManager.GetString("WeatherMainlyClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcast.
        /// </summary>
        public static string WeatherOvercast {
            get {
                return ResourceManager.GetString("WeatherOvercast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partly Cloudy.
        /// </summary>
        public static string WeatherPartlyCloudy {
            get {
                return ResourceManager.GetString("WeatherPartlyCloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain.
        /// </summary>
        public static string WeatherRain {
            get {
                return ResourceManager.GetString("WeatherRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string WeatherSnow {
            get {
                return ResourceManager.GetString("WeatherSnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm.
        /// </summary>
        public static string WeatherThunderstorm {
            get {
                return ResourceManager.GetString("WeatherThunderstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string WeatherUnknown {
            get {
                return ResourceManager.GetString("WeatherUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind: {0} km/h.
        /// </summary>
        public static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
    }
}
